//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeogradskaFilharmonijaModelEntities : DbContext
    {
        public BeogradskaFilharmonijaModelEntities()
            : base("name=BeogradskaFilharmonijaModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clan_klubaSet> clan_klubaSet { get; set; }
        public virtual DbSet<djakSet> djakSet { get; set; }
        public virtual DbSet<dvoranaSet> dvoranaSet { get; set; }
        public virtual DbSet<izvodjenjeSet> izvodjenjeSet { get; set; }
        public virtual DbSet<kartaSet> kartaSet { get; set; }
        public virtual DbSet<koncertSet> koncertSet { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<orkestarSet> orkestarSet { get; set; }
        public virtual DbSet<penzionerSet> penzionerSet { get; set; }
        public virtual DbSet<posetilacSet> posetilacSet { get; set; }
        public virtual DbSet<salaSet> salaSet { get; set; }
        public virtual DbSet<sef_dirigentSet> sef_dirigentSet { get; set; }
        public virtual DbSet<Statistic> Statistic { get; set; }
        public virtual DbSet<studentSet> studentSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
