//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Collections.Generic;
    
    public partial class clan_klubaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clan_klubaSet()
        {
            this.djakSet = new HashSet<djakSet>();
            this.penzionerSet = new HashSet<penzionerSet>();
            this.studentSet = new HashSet<studentSet>();
        }
    
        public decimal sfr { get; set; }
        public string jmbg { get; set; }
        public string korime { get; set; }
        public string datrodj { get; set; }
        public string imeck { get; set; }
        public string prezck { get; set; }
        public decimal posetilac_brckar_clan_kluba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<djakSet> djakSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<penzionerSet> penzionerSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentSet> studentSet { get; set; }
        public virtual posetilacSet posetilacSet { get; set; }
    }
}
