//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvodjenjeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izvodjenjeSet()
        {
            this.kartaSet = new HashSet<kartaSet>();
        }
    
        public decimal sala_dvorana_iddvor_izvodjenje { get; set; }
        public decimal sala_idsal_izvodjenje { get; set; }
        public decimal koncert_idkon_izvodjenje { get; set; }
        public decimal sala_idsal { get; set; }
        public decimal sala_dvorana_iddvor_sala { get; set; }
    
        public virtual salaSet salaSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kartaSet> kartaSet { get; set; }
        public virtual koncertSet koncertSet { get; set; }
    }
}
