//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public string KorisnickoIme { get; set; }
        public string Sifra { get; set; }
        public string Uloga { get; set; }
        public Nullable<int> Odobreno { get; set; }
    }
}
