//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salaSet()
        {
            this.izvodjenjeSet = new HashSet<izvodjenjeSet>();
        }
    
        public decimal idsal { get; set; }
        public decimal brsed { get; set; }
        public string velsce { get; set; }
        public decimal dvorana_iddvor_sala { get; set; }
        public decimal dvorana_iddvor { get; set; }
    
        public virtual dvoranaSet dvoranaSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvodjenjeSet> izvodjenjeSet { get; set; }
    }
}
