//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeogradskaFilharmonija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int ID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> StatisticDate { get; set; }
    }
}
